"""Builds a self-contained HTML report from one or more campaign runs.

No external JS/CSS dependencies -- this needs to render standalone from a
laptop with no network during a hackathon demo.
"""
from __future__ import annotations

import html
from collections import defaultdict
from pathlib import Path
from typing import Dict, List

from .attacks import CATEGORY_WEIGHT

SEVERITY_COLOR = {0: "#3fb950", 1: "#d4a72c", 2: "#e3a008", 3: "#e8590c", 4: "#c92a2a"}


def _run_summary(findings: List[dict]) -> Dict:
    total = len(findings)
    violated = [f for f in findings if f["violated"]]
    by_category = defaultdict(lambda: {"total": 0, "violated": 0, "max_sev": 0})
    for f in findings:
        c = by_category[f["category"]]
        c["total"] += 1
        if f["violated"]:
            c["violated"] += 1
            c["max_sev"] = max(c["max_sev"], f["severity"])
    return {
        "total": total,
        "violated": len(violated),
        "success_rate": (len(violated) / total * 100) if total else 0,
        "by_category": dict(by_category),
    }


def build_report(runs: Dict[str, List[dict]], out_path: str | Path, title: str = "AegisOps Red-Team Report") -> Path:
    """`runs` maps a run label (e.g. 'baseline', 'post-patch') to its findings."""
    out_path = Path(out_path)
    summaries = {label: _run_summary(f) for label, f in runs.items()}

    parts = [f"""<!doctype html><html><head><meta charset="utf-8">
<title>{html.escape(title)}</title>
<style>
body {{ font-family: -apple-system, Segoe UI, sans-serif; background:#0d1117; color:#e6edf3; margin:0; padding:24px 32px; }}
h1 {{ font-size: 1.4rem; margin-bottom: 4px; }}
.sub {{ color:#8b949e; margin-bottom:24px; }}
.run {{ background:#161b22; border:1px solid #30363d; border-radius:10px; padding:20px; margin-bottom:24px; }}
.run h2 {{ margin-top:0; font-size:1.1rem; }}
.stat-row {{ display:flex; gap:24px; margin-bottom:16px; flex-wrap:wrap; }}
.stat {{ background:#0d1117; border:1px solid #30363d; border-radius:8px; padding:10px 16px; min-width:120px; }}
.stat .num {{ font-size:1.6rem; font-weight:700; }}
.stat .label {{ color:#8b949e; font-size:0.8rem; }}
table {{ width:100%; border-collapse:collapse; font-size:0.9rem; }}
th, td {{ text-align:left; padding:6px 10px; border-bottom:1px solid #21262d; }}
th {{ color:#8b949e; font-weight:500; }}
.bar-bg {{ background:#21262d; border-radius:4px; height:10px; width:100%; overflow:hidden; }}
.bar-fg {{ height:100%; }}
.sev {{ display:inline-block; width:10px; height:10px; border-radius:50%; margin-right:6px; }}
</style></head><body>
<h1>{html.escape(title)}</h1>
<div class="sub">Generated by aegis-redteam — closed-loop adversarial testing for a self-improving agent.</div>
"""]

    for label, findings in runs.items():
        s = summaries[label]
        parts.append(f'<div class="run"><h2>Run: {html.escape(label)}</h2>')
        parts.append('<div class="stat-row">')
        parts.append(f'<div class="stat"><div class="num">{s["total"]}</div><div class="label">seeds tested</div></div>')
        parts.append(f'<div class="stat"><div class="num">{s["violated"]}</div><div class="label">confirmed violations</div></div>')
        parts.append(f'<div class="stat"><div class="num">{s["success_rate"]:.0f}%</div><div class="label">attack success rate</div></div>')
        parts.append('</div>')

        parts.append('<table><tr><th>Category</th><th>Tested</th><th>Violated</th><th>Max severity</th><th></th></tr>')
        for cat, c in sorted(s["by_category"].items(), key=lambda kv: -kv[1]["max_sev"]):
            pct = (c["violated"] / c["total"] * 100) if c["total"] else 0
            color = SEVERITY_COLOR.get(c["max_sev"], "#8b949e")
            parts.append(
                f'<tr><td>{html.escape(cat)}</td><td>{c["total"]}</td><td>{c["violated"]}</td>'
                f'<td><span class="sev" style="background:{color}"></span>{c["max_sev"]}</td>'
                f'<td style="width:30%"><div class="bar-bg"><div class="bar-fg" style="width:{pct:.0f}%;background:{color}"></div></div></td></tr>'
            )
        parts.append('</table></div>')

    # Top findings across all runs
    all_violations = []
    for label, findings in runs.items():
        for f in findings:
            if f["violated"]:
                all_violations.append((label, f))
    all_violations.sort(key=lambda lf: -lf[1]["severity"])

    if all_violations:
        parts.append('<div class="run"><h2>Top findings</h2><table><tr><th>Run</th><th>Seed</th><th>Category</th><th>Severity</th><th>Rationale</th></tr>')
        for label, f in all_violations[:15]:
            parts.append(
                f'<tr><td>{html.escape(label)}</td><td>{html.escape(f["seed_id"])}</td>'
                f'<td>{html.escape(f["category"])}</td><td>{f["severity"]}</td>'
                f'<td>{html.escape(f["rationale"])}</td></tr>'
            )
        parts.append('</table></div>')

    parts.append("</body></html>")
    out_path.write_text("".join(parts))
    return out_path
